import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Obfuscate from 'react-obfuscate';
import { Email } from "react-obfuscate-email";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.wrapper}>
          <span>Phone: <Obfuscate tel="205-454-1234" /></span>
          <span>Email: <Obfuscate email="reanderagulto29@gmail.com" /></span>
          <span>
            <Obfuscate email="hello@coston.io" aria-label="Email Me">
              <svg width={24} height={21}>
                <path
                  fill="#000"
                  d="M12 12.713L.0 3h23.97L12 12.713zm0 2.574L0 5.562V21h24V5"
                />
              </svg>
            </Obfuscate>
          </span>
          <span>
            <Email email="reanderagulto29@gmail.com">
              Email me!
            </Email>
          </span>
        </div>
      </main>
    </>
  )
}
